# Generated by Django 3.2.5 on 2021-07-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=200, verbose_name='sobrenome')),
                ('data_nascimento', models.DateField(null=True, verbose_name='data nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo')),
                ('medico', models.CharField(max_length=200, verbose_name='médico responsável')),
                ('prontuario', models.IntegerField(unique=True, verbose_name='número do prontuário')),
                ('convenio', models.CharField(max_length=200, verbose_name='convênio')),
                ('whatsapp', models.CharField(max_length=15, null=True, unique=True, verbose_name='número do whatsapp')),
                ('whatsapp_h', models.CharField(max_length=30, null=True, unique=True, verbose_name='número do whatsapp higienizado')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data de Registro Paciente')),
                ('parentesco', models.CharField(choices=[('H', 'Nenhum'), ('T', 'Tio(a)'), ('S', 'Sobrinho(a)'), ('A', 'Amigo(a)'), ('P', 'Primo(a)'), ('I', 'Irmão/Irmã'), ('J', 'Cônjuge'), ('F', 'Filho(a)'), ('C', 'Cuidador(ra)'), ('O', 'Outros'), ('N', 'Neto(a)')], default='H', max_length=1, verbose_name='Grau parentesco')),
                ('nome_parente', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nome do parente')),
            ],
            options={
                'unique_together': {('prontuario', 'whatsapp')},
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portabilidade_Whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=15, null=True)),
                ('data_modificacao', models.DateField(auto_now_add=True)),
                ('id_pasciente_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_destino', to='todo.pasciente')),
                ('id_pasciente_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_origem', to='todo.pasciente')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='nome usuario')),
                ('name', models.CharField(max_length=200, verbose_name='nome usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
